#ifndef QGCINPUTS
#define QGCINPUTS

enum QGC_INPUT_MODE {
    QGC_INPUT_MODE_NONE=0,
    QGC_INPUT_MODE_MOUSE=1,
    QGC_INPUT_MODE_TOUCH=2,
    QGC_INPUT_MODE_KEYBOARD=4,
    QGC_INPUT_MODE_XBOX=8
};

#endif // QGCINPUTS

